### ISSUE TITLE
The insights are not being translated to French

### ISSUE THREAD

**Issue by Najib90** [mearashadowfax/ScrewFast#130]
**Issue Description:**
The issue is that everything (except some buttons that say "Read More") is set up with i18n in mind, having the website translated into French as the default language. However, the insights section below the Blog has been skipped and does not get translated accordingly.

**Details:**
The blog itself and other sections correctly implement i18n and switch languages based on the user's locale.
The insights section does not translate its content according to the selected language.
Buttons such as "Read More" in the insights section are also not translated, although I was able to fix this

**Steps to Reproduce:**
Set the website to a non-default language (e.g., French).
Navigate to the insights section.
Observe that the main content of the insights section is not translated.

**Expected Behaviour:**
The insights section should be translated according to the selected language, just like the other sections of the website.

**Request for Assistance:**
Any tips on how to implement i18n for the insights section to ensure it gets translated accordingly would be highly appreciated. In addition, having this standard translated into the template would make the template more robust.

**Comment by mearashadowfax** [comment]
Hello @Najib90! This issue is straightforward to resolve. You need to translate the insights content or any other content collections into your preferred language and create corresponding directories, just like we did with the blog content collection. I’ve already added translations in the recent update for convenience.

**Comment by Najib90** [comment]
Thank you, however, when I do that it repeats both the insights for the English and French ones. So below the blog which works in the two different languages separately, it shows 6 insights for me for some reason. And I had done what you are suggesting before already. 

Is there any other file you had changed or just added the folders and that's it?

**Comment by mearashadowfax** [comment]
> Thank you, however, when I do that it repeats both the insights for the English and French ones. So below the blog which works in the two different languages separately, it shows 6 insights for me for some reason. And I had done what you are suggesting before already.
> 
> Is there any other file you had changed or just added the folders and that's it?

Please check the `index.astro` file for each language in your blog directory: [/src/pages/blog/index.astro](https://github.com/mearashadowfax/ScrewFast/tree/main/src/pages/blog). 

After we added directories for content collections, we should ensure that we are fetching the correct collection for each language. For example, you can modify the code to fetch only the English insights like this:

```
const englishInsightsEntries = await getCollection("insights", ({ id }) => {
  return id.startsWith("en/");
});
```

And for the French insights at `src/pages/fr/blog/index.astro`, you would use:

```
const frenchInsightsEntries = await getCollection("insights", ({ id }) => {
  return id.startsWith("fr/");
});
```

**Comment by Najib90** [comment]
> > Thank you, however, when I do that it repeats both the insights for the English and French ones. So below the blog which works in the two different languages separately, it shows 6 insights for me for some reason. And I had done what you are suggesting before already.
> > Is there any other file you had changed or just added the folders and that's it?
> 
> Please check the `index.astro` file for each language in your blog directory: [/src/pages/blog/index.astro](https://github.com/mearashadowfax/ScrewFast/tree/main/src/pages/blog).
> 
> After we added directories for content collections, we should ensure that we are fetching the correct collection for each language. For example, you can modify the code to fetch only the English insights like this:
> 
> ```
> const englishInsightsEntries = await getCollection("insights", ({ id }) => {
>   return id.startsWith("en/");
> });
> ```
> 
> And for the French insights at `src/pages/fr/blog/index.astro`, you would use:
> 
> ```
> const frenchInsightsEntries = await getCollection("insights", ({ id }) => {
>   return id.startsWith("fr/");
> });
> ```

Thank you this works, although I would stick with just keeping the name as-is so not to introduce a breaking change if someone else reads this:

// Get all insights posts
const insightPosts: CollectionEntry<"insights">[] =
  await getCollection("insights", ({ id }) => {
    return id.startsWith("fr/");
  });
