### ISSUE TITLE
404 Page Not Redirecting to French Version When Language is Switched

### ISSUE THREAD

**Issue by Najib90** [mearashadowfax/ScrewFast#131]
**Issue Description:**
The issue is that when the website is switched to the French version and a user navigates to a non-existent page, the 404 page is still displayed in English instead of French.

**Details:**
The website's language is switched to French.
When navigating to a non-existent page (triggering a 404 error), the 404 page is displayed in English.
The expected behavior is that the 404 page should be displayed in French when the website is set to the French language.

**Steps to Reproduce:**
Switch the website language to French.
Navigate to a non-existent page to trigger the 404 error.
Observe that the 404 page is displayed in English.
Expected Behavior:
The 404 page should be displayed in French when the website is set to the French language.

**Request for Assistance:**
Any guidance on how to ensure the 404 page respects the selected language setting and displays the appropriate language content would be highly appreciated. In addition, it would be good to have it properly set up in the theme already.

**Comment by mearashadowfax** [comment]
Hi @Najib90. I’ve added code to dynamically generate the 404 page content based on the current language setting. If you have many languages to support, you can also use a JSON, or a CMS to retrieve the translated strings. However, while it works locally, looks like localized 404 pages are a bit tricky, so it will require a manual set-up on your host.

**Comment by mearashadowfax** [comment]
Closing for now.

**Comment by Najib90** [comment]
Thank you, understood!
