### ISSUE TITLE
Swiper in ScrewFast

### ISSUE THREAD

**Issue by garg-udit** [mearashadowfax/ScrewFast#135]
I tried to use Swiper in "Screwfast", but failed to do so, could you please help me in getting it done.
I just want to know which path will be great to achieve this functionality.
Please reply asap.
ThankYou.

**Comment by mearashadowfax** [comment]
Hi @garg-udit, to use Swiper in "Screwfast," you can follow these steps:

Install Swiper:
```
npm install swiper
```

Import Swiper into your component:

```
<script>
  import Swiper from 'swiper';
  import { Pagination, EffectCards } from 'swiper/modules';

  const swiper = new Swiper('.mySwiper', {
    modules: [Pagination, EffectCards],
    effect: 'cards',
    grabCursor: true,
    centeredSlides: true,
    pagination: {
      el: '.swiper-pagination',
      dynamicBullets: true,
    },
    rewind: true,
  });
</script>
```

Import Swiper styles in the page where your component is located:

```
---
// Styles
import 'swiper/css/bundle';
---
```
This should help you integrate Swiper into your project successfully.

**Comment by garg-udit** [comment]
@mearashadowfax 
Thank you so much Emil for helping me out.
