### ISSUE TITLE
BrandLogo.astro not displaying images on Cloudflare Pages

### ISSUE THREAD

**Issue by Najib90** [mearashadowfax/ScrewFast#151]
### Discussed in https://github.com/mearashadowfax/ScrewFast/discussions/150

<div type='discussions-op-text'>

<sup>Originally posted by **Najib90** July 27, 2024</sup>
**Description**
I modified the BrandLogo.astro file to accept both PNG and SVG files. The changes work correctly in the development environment, but after deploying the website to Cloudflare Pages, the images do not display and instead show a question mark icon.

**Steps to Reproduce**

1. Modify BrandLogo.astro as shown below.
2. Test in the development environment (images display correctly).
3. Deploy the site to Cloudflare Pages.
4. Notice the images not displaying and showing a question mark icon instead.

```
---
const { class: className } = Astro.props;
---
<div class="{TestBrandLogo}">
  <img src="/src/images/icon.png" alt="Brand Logo" class="{TestBrandLogo} dark:hidden" style="height: 30px;" />
  <img src="/src/images/icon_svg_test.svg" alt="Brand Logo" class="{TestBrandLogo} hidden dark:block" style="height: 30px;" /> 
</div>
```

**Attempts to Fix**

- Tried using both PNG and SVG formats.
- Verified the image paths are correct.

**Expected Behavior**
Images should display correctly both in the development environment and on Cloudflare Pages.

**Actual Behavior**
Images display correctly in the development environment but show a question mark icon after deployment to Cloudflare Pages.

**Question**
Any ideas on what might be going wrong or how to fix this issue?</div>

**Comment by mearashadowfax** [comment]
In .astro files, local images must be imported into the file to be used. Remote and public/ images do not require importing. Maybe the problem lies somewhere here. Have you tried storing them in the `public/` directory and using:

```
<img src="/logos/icon.png" alt="Brand Logo">
```

or importing them like this:

```
import iconPng from '/images/icon.png';
---
<Image src={iconPng} alt="Brand Logo" />
```

**Comment by Najib90** [comment]
> In .astro files, local images must be imported into the file to be used. Remote and public/ images do not require importing. Maybe the problem lies somewhere here. Have you tried storing them in the `public/` directory and using:
> 
> ```
> <img src="/logos/icon.png" alt="Brand Logo">
> ```
> 
> or importing them from src/ like this:
> 
> ```
> import iconPng from '/images/icon.png';
> ---
> <Image src={iconPng} alt="Brand Logo" />
> ```

I tried both ways, but unfortunately they didn't work.

**Comment by mearashadowfax** [comment]
>I tried both ways, but unfortunately they didn't work.

I've created a test repository on Cloudflare Pages, and it is displaying the logos. I used the same image in a different format, so you won't see the difference; however, everything works fine.

![Screenshot 2024-07-27 200937](https://github.com/user-attachments/assets/79ce780a-4a68-4672-acf4-17ff9e247fa3)
![Screenshot 2024-07-27 200957](https://github.com/user-attachments/assets/0ca7b71c-fe20-4f33-8a0e-3eef191f937f)

**Comment by Najib90** [comment]
> > I tried both ways, but unfortunately they didn't work.
> 
> I've created a test Page on Cloudflare Pages, and it is displaying the logos. I used the same image in a different format, so you won't see the difference; however, everything works fine.
> 
> ![Screenshot 2024-07-27 200937](https://private-user-images.githubusercontent.com/125820963/352764364-79ce780a-4a68-4672-acf4-17ff9e247fa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTc0MTEsIm5iZiI6MTcyMjA5NzExMSwicGF0aCI6Ii8xMjU4MjA5NjMvMzUyNzY0MzY0LTc5Y2U3ODBhLTRhNjgtNDY3Mi1hY2Y0LTE3ZmY5ZTI0N2ZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxNjE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDQxZGNhNTRmNmRmNWQxNzMwN2I3ZTdhNjFmYWFlMmJhM2M3MDU3YzZhZTQ3M2QzODMwNTk2NTU0NmVjZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uQAv3PtezMIQ0qn97yLgMnFecEIz-E3Rt0KMtzVrOes) ![Screenshot 2024-07-27 200957](https://private-user-images.githubusercontent.com/125820963/352764365-0ca7b71c-fe20-4f33-8a0e-3eef191f937f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTc0MTEsIm5iZiI6MTcyMjA5NzExMSwicGF0aCI6Ii8xMjU4MjA5NjMvMzUyNzY0MzY1LTBjYTdiNzFjLWZlMjAtNGYzMy04YTBlLTNlZWYxOTFmOTM3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxNjE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTM4NWE0OTNjNTI3YzM5YzNkYjhhZmYyYWYzMWI2MDU1MjM2NjAxNDZmYWVhMTQwOWQ0MTU0YTdkZjUyNjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jcovj7ENNvX12wEEX9MoAyvAywJf4hTASylKddH0uyg)

Which way did you end up using then? Because I tried even now with directly in the Navbar.astro file. Or are there limitations and I need to be careful with e.g. the size of the file? Are you able to share that png file you've used then? Or is it a different extension image?

**Comment by mearashadowfax** [comment]
> Which way did you end up using then? Because I tried even now with directly in the Navbar.astro file. Or are there limitations and I need to be careful with e.g. the size of the file? Are you able to share that png file you've used then? Or is it a different extension image?

I used the files located in `src/images/icon.png` and `src/images/icon.svg`, trying two methods: moving them to the `public/` directory and importing them from the `src/images` directory, latter is below:
```
---
import iconSVG from "@images/icon.svg";
import iconpng from "@images/icon.png";
---
<div class="{TestBrandLogo}">
  <img src={iconSVG.src} alt="Brand Logo" class="{TestBrandLogo} dark:hidden" style="height: 30px;" />
  <img src={iconpng.src} alt="Brand Logo" class="{TestBrandLogo} hidden dark:block" style="height: 30px;" /> 
</div>
```

Both of them worked for me.

**Comment by Najib90** [comment]
> > Which way did you end up using then? Because I tried even now with directly in the Navbar.astro file. Or are there limitations and I need to be careful with e.g. the size of the file? Are you able to share that png file you've used then? Or is it a different extension image?
> 
> I used the files located in `src/images/icon.png` and `src/images/icon.svg`, trying two methods: moving them to the `public/` directory and importing them from the `src/images` directory, latter is below:
> 
> ```
> ---
> import iconSVG from "@images/icon.svg";
> import iconpng from "@images/icon.png";
> ---
> <div class="{TestBrandLogo}">
>   <img src={iconSVG.src} alt="Brand Logo" class="{TestBrandLogo} dark:hidden" style="height: 30px;" />
>   <img src={iconpng.src} alt="Brand Logo" class="{TestBrandLogo} hidden dark:block" style="height: 30px;" /> 
> </div>
> ```
> 
> Both of them worked for me. File size shouldn't be the issue, however I would try some other files as well for testing.

Many thanks. I forgot to say ".src" after the "iconpng". This solved it for me!
