### ISSUE TITLE
feature request can we have outline or toc of blog

### ISSUE THREAD

**Issue by wanghaisheng** [mearashadowfax/ScrewFast#164]
whether in the top of blog content or left side

**Comment by mearashadowfax** [comment]
Hi @wanghaisheng! You can use the insights template as your blog, which already has a toc on the left side, in addition you can move it to the right or top, and add additional components from the blog page.

**Comment by wanghaisheng** [comment]
can you share a url of insights

**Comment by mearashadowfax** [comment]
Here it is: https://screwfast.uk/insights/en/insight-1/

**Comment by wanghaisheng** [comment]
i  manage to find this under same level of blog ,and url seems weired ,does this should be /en/xxxx/xxx
and if you go to blog in fr and click any blog ,you will found url  is https://screwfast.uk/fr/blog/fr/post-2/
fr will be duplicate

**Comment by mearashadowfax** [comment]
That's correct, the default language in this case is English, so we don't prefix it, however we prefix French. And then each blog or insights content collections also have their own language prefixes, so it's blog/en and blog/fr.
