### ISSUE TITLE
Help Needed: Loading localized content in Astro pages

### ISSUE THREAD

**Issue by dwr-studio** [mearashadowfax/ScrewFast#168]
Hello,

First of all, thank you for this fantastic theme! It’s truly inspiring.

I’m currently working on loading localized content for pages like the homepage using Astro’s markdown functions instead of passing the translated content as a component property. My goal is to write content in markdown and load it correctly based on the locale.

Here’s the folder structure I’m working with:
```
/content
  └── /homepage
      ├── /en
      │   └── index.md
      └── /fr
          └── index.md
```

However, I’m having trouble figuring out how to load the correct content in the `pages/index.astro` file.

Has anyone tried this approach before or have any suggestions on where to start? I’m eager to contribute this alternative solution and would greatly appreciate any guidance or hints.

Thank you in advance for your help!

**Comment by mearashadowfax** [comment]
Hi there, @dwr-studio! Thank you for the kind words, I'm glad you're enjoying the theme. It should work similarly for both `.astro` page components and Markdown/MDX files within the `src/pages/` directory, as they automatically become pages on your website. If you're working with a Content Collection, you could use something like this:

```
---
import { getEntryBySlug } from 'astro:content';

const locale = Astro.url.pathname.startsWith('/fr') ? 'fr' : 'en';
const homepageContent = await getEntryBySlug('homepage', locale + '/index');
---
<main>
  <h1>{homepageContent.data.title}</h1>
  <div>{homepageContent.content}</div>
</main>
```

Also, Astro recently added an option to implement your own routing logic manually, which looks promising, though I haven't had the chance to try it out yet:  https://docs.astro.build/en/guides/internationalization/#manual
