### ISSUE TITLE
submission form?

### ISSUE THREAD

**Issue by 520qianjiawen** [mearashadowfax/ScrewFast#169]
Great theme, but how do I configure the submission form?

**Comment by mearashadowfax** [comment]
Hi @520qianjiawen! There are a few recipes and guides out there, here are a few: 
- https://docs.astro.build/en/recipes/build-forms/
- https://docs.astro.build/en/recipes/build-forms-api/
- https://mfrachet.com/blog/en/astro-progressively-enhanced-forms
