### ISSUE TITLE
how to ajust toc 

### ISSUE THREAD

**Issue by wanghaisheng** [mearashadowfax/ScrewFast#178]
current it takes more than half of screen width,
![image](https://github.com/user-attachments/assets/8a4a52cd-4241-455e-b10c-b50d9b864470)

a good example is like this

![image](https://github.com/user-attachments/assets/bb46e504-ad25-4cb2-a0e3-6576e7d5db48)

**Comment by mearashadowfax** [comment]
Add "md:grid-cols-3" to the parent container and "col-start-2 col-span-2" to the second div child, for example, or however you want it to look:
![localhost_4321_insights_en_insight-2_](https://github.com/user-attachments/assets/55ecb154-fb7f-4466-bd27-b64d9850896f)

**Comment by wanghaisheng** [comment]
what do you mean by parent and second

i  have copy insights and borrow a little bit from blog to this
https://github.com/wanghaisheng/priceresonance/blob/main/src/pages/blogs/%5B...slug%5D.astro

and you can see

https://b161568b.priceresonance.pages.dev/blogs/en/tools-for-building-saas-price-plan-dataset/
tags  author are not centered,

try to add you mentioned ,not working

**Comment by mearashadowfax** [comment]
This is the parent: **https://github.com/wanghaisheng/priceresonance/blob/8c16ebe7d995c9b611ad6f69b20f3f5bf21f3646/src/pages/blogs/%5B...slug%5D.astro#L113**

So you should add "md:grid-cols-3" as a class, for example. Then align the tags, author, share button, etc. using classes.

**Comment by wanghaisheng** [comment]
thanks i will go to ask claude, css is difficult for me

**Comment by wanghaisheng** [comment]
@mearashadowfax  last question is about the logo  svg generation ,which tool do you use ,i want a similar one

**Comment by mearashadowfax** [comment]
> @mearashadowfax last question is about the logo svg generation ,which tool do you use ,i want a similar one

I was using Figma.
