### ISSUE TITLE
TypeScript Errors When Including Google Ads Script in MainLayout.astro File

### ISSUE THREAD

**Issue by Najib90** [mearashadowfax/ScrewFast#265]
**Title:** TypeScript Errors When Including Google Ads Script in `MainLayout.astro` File

**Description:**

Hello,

I'm trying to include the Google Ads tracking script in my Astro project, specifically within the `MainLayout.astro` file. However, I'm encountering TypeScript errors when I add the following script:

```astro
<!-- MainLayout.astro -->
<html>
  <head>
    <!-- Other head elements -->
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'AW-29387293872');
    </script>
  </head>
  <body>
    <!-- Page content -->
    <slot />
  </body>
</html>
```

The TypeScript warnings I'm receiving are:

- **Error:** `Property 'dataLayer' does not exist on type 'Window & typeof globalThis'.` *(ts2339)*
  - Occurs on the line: `window.dataLayer = window.dataLayer || [];`

- **Error:** `Expected 0 arguments, but got 2.` *(ts2554)*
  - Occurs on the line: `gtag('js', new Date());`
  - Similar error for `gtag('config', 'AW-29387293872');`

**Steps to Reproduce:**

1. Create a new Astro project.
2. Open the `MainLayout.astro` file.
3. Insert the Google Ads script into the `<head>` section.
4. Observe the TypeScript errors in the editor or during the build process.

**Expected Behavior:**

The Google Ads tracking script should be included without TypeScript errors, functioning as intended.

**Actual Behavior:**

TypeScript reports errors about undefined properties and incorrect function arguments, which may prevent the script from working properly.

**Additional Context:**

- **Astro Version:** v4.8.6
- **Development Environment:** VSCode
- **Operating System:** MacOS Macbook Air M1

**Question:**

Is there a recommended way to include external scripts like the Google Ads tracking code in an Astro project's `MainLayout.astro` file without encountering these TypeScript errors? Should I add specific type definitions or adjust the script to be compatible with TypeScript in Astro?

Any guidance would be greatly appreciated. Thank you!

**Comment by mearashadowfax** [comment]
Hey @Najib901! Have you tried using `<script is:inline>`?

**Comment by Najib90** [comment]
> Hey @Najib901! Have you tried using `<script is:inline>`?

Hello, yes I did. This is what I have in my code:
<script is:inline>
  if (typeof window !== "undefined") {
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      window.dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'AW-29387293872');
  }
</script>

And this is when I test it out on Google Ads:
Your Google tag wasn’t detected on your website. Follow the instructions and try again.

**Comment by mearashadowfax** [comment]
Thanks for sharing your code snippet. Unfortunately, I don't have experience with Google Ads, so I recommend checking their docs or exploring solutions online.

**Comment by mearashadowfax** [comment]
@Najib90, you may want to take a look at this, perhaps using Partytown could help:

- https://stackoverflow.com/questions/75444681/how-to-make-gtag-and-gtm-work-with-partytown-in-a-react-app
- https://partytown.builder.io/
