### ISSUE TITLE
Add tables to product pages and blog pages to display errors

### ISSUE THREAD

**Issue by 520qianjiawen** [mearashadowfax/ScrewFast#58]
<img width="1439" alt="image" src="https://github.com/mearashadowfax/ScrewFast/assets/47584744/2d99ab21-afcb-4280-b4b8-0ef66cea8300">

**Comment by mearashadowfax** [comment]
Thanks @520qianjiawen for opening an issue! I've added a `tableData` frontmatter property in Markdown. This allows you to switch between `specificationsRight` and `tableData`, removing one or the other as necessary.
![image](https://github.com/mearashadowfax/ScrewFast/assets/125820963/aee7b83b-f058-4cc3-9f85-45bbbdb6d754)

**Comment by mearashadowfax** [comment]
Added in PR #60
